Repository AY1920S1-CS2113T-F09-4/main, pull requests merged in 2019-10, with the labels that each got.

#60 Update Duke to add Classes for new idea
  data/todo_list.txt
  src/main/java/duke/Parser.java
  src/main/java/duke/components/Bar.java
  src/main/java/duke/components/Chord.java
  src/main/java/duke/components/Group.java
  src/main/java/duke/components/Note.java
  src/main/java/duke/components/Pitch.java
  src/main/java/duke/components/Song.java
Labels: priority.High, type.Story

#63 Complete A-Jar
  src/main/java/duke/TaskList.java
Labels: priority.High

#68 Add SongList class
  src/main/java/duke/Duke.java
  src/main/java/duke/TaskList.java
  src/main/java/duke/Ui.java
  src/main/java/duke/commands/AddBarCommand.java
  src/main/java/duke/commands/AddCommand.java
  src/main/java/duke/commands/ByeCommand.java
  src/main/java/duke/commands/Command.java
  src/main/java/duke/commands/DeleteCommand.java
  src/main/java/duke/commands/DoneCommand.java
  src/main/java/duke/commands/FindCommand.java
  src/main/java/duke/commands/HelpCommand.java
  src/main/java/duke/commands/ListCommand.java
  src/main/java/duke/commands/NewCommand.java
  src/main/java/duke/commands/RemindCommand.java
  src/main/java/duke/commands/ViewCommand.java
  src/main/java/duke/components/SongList.java
Labels: priority.High

#71 Plan Storage class and include basic functions
  src/main/java/duke/Storage.java
Labels: priority.High, severity.High, type.Bug

#113 Ascii Command Done Up (Minor bug fixed)
  src/main/java/duke/Duke.java
  src/main/java/duke/DukeException.java
  src/main/java/duke/commands/AsciiCommand.java
  src/main/java/duke/commands/CopyCommand.java
  src/main/java/duke/commands/GroupCommand.java
  src/main/java/duke/components/VerseList.java
Labels: type.Enhancement

#133 JavaFX Base is up and displays current song
  build.gradle
  src/main/java/ducats/Ducats.java
  src/main/java/ducats/DucatsGui.java
  src/main/java/ducats/uicomponents/CommandLine.java
  src/main/java/ducats/uicomponents/DucatsWindow.java
  src/main/resources/fxml/ducatswindow.fxml
  src/main/resources/style/ducats.css
  src/main/resources/style/persistent-prompt.css
  src/main/resources/view/DucatsMainWindow.fxml
  src/main/resources/view/MainWindow.fxml
Labels: type.Enhancement

#140 Add folder for PlantUML diagrams
  docs/diagrams/SongList.puml
  src/main/java/ducats/Parser.java
Labels: type.Task

#148 Update to fix parsing error
  src/main/java/ducats/components/WordGetter.java
Labels: priority.High, severity.High, type.Bug
